"""The generator, not the generated output — `resources/*.py` are its
product. `scripts/codegen.sh` and `odyssey sdk codegen`/`check-drift`
both call this module; nothing else should hand-edit `resources/*.py`.

Deliberately narrow: this repo's `services/api` exposes only `GET`
endpoints today (item 8.2), each returning either one object or an array
of one object type, with at most one path parameter. The generator
raises rather than silently guessing on anything outside that shape —
the same "narrow but real, not speculative" discipline every other
codegen-shaped module in this repo follows (`odyssey_dataprep.datasets`,
`odyssey_eval.runner`'s dynamic metric loading, etc).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Tuple

__all__ = ["render_resource", "generate", "check_drift"]

_REPO_ROOT = Path(__file__).resolve().parents[4]
_OPENAPI_PATH = _REPO_ROOT / "services" / "api" / "openapi.json"
_RESOURCES_DIR = Path(__file__).resolve().parent / "resources"

_BANNER = (
    '"""AUTO-GENERATED by `odyssey sdk codegen` (odyssey_sdk.codegen) from\n'
    'services/api/openapi.json. Do not edit by hand — see codegen.py.\n"""\n'
)


class UnsupportedOperationError(NotImplementedError):
    pass


def _singular(word: str) -> str:
    return word[:-1] if word.endswith("s") else word


def _model_ref(schema: Dict[str, Any]) -> Tuple[str, bool]:
    if schema.get("type") == "array":
        return schema["items"]["$ref"].rsplit("/", 1)[-1], True
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1], False
    raise UnsupportedOperationError(f"unsupported response schema: {schema}")


def load_openapi() -> Dict[str, Any]:
    return json.loads(_OPENAPI_PATH.read_text(encoding="utf-8"))


def _operations_by_resource(
    openapi: Dict[str, Any],
) -> Dict[str, List[Tuple[str, str, List[str], str, bool]]]:
    """``{resource: [(method_name, path, path_params, model, is_list), ...]}``.

    ``resource`` is a path's first segment (``/journeys/{id}`` and
    ``/journeys`` both belong to ``journeys``); ``/health`` has no
    resource grouping and is skipped here (hand-written on `OdysseySDK`
    itself — see `client.py`).
    """
    by_resource: Dict[str, List[Tuple[str, str, List[str], str, bool]]] = {}
    for path, methods in sorted(openapi["paths"].items()):
        segments = [s for s in path.split("/") if s]
        if segments == ["health"]:
            continue
        if list(methods.keys()) != ["get"]:
            raise UnsupportedOperationError(
                f"{path}: only a single GET operation per path is supported, got {list(methods)}"
            )
        op = methods["get"]
        params = [p["name"] for p in op.get("parameters", []) if p.get("in") == "path"]
        if len(params) > 1:
            raise UnsupportedOperationError(f"{path}: more than one path parameter")
        schema = op["responses"]["200"]["content"]["application/json"]["schema"]
        model, is_list = _model_ref(schema)

        resource = segments[0]
        method_name = "get" if params else "list"
        by_resource.setdefault(resource, []).append(
            (method_name, path, params, model, is_list)
        )
    return by_resource


def render_resource(
    resource: str, ops: List[Tuple[str, str, List[str], str, bool]]
) -> str:
    models = sorted({model for _, _, _, model, _ in ops})
    class_name = "".join(p.capitalize() for p in resource.split("_")) + "Resource"

    lines = [_BANNER, "from __future__ import annotations", ""]
    if any(is_list for _, _, _, _, is_list in ops):
        lines += ["from typing import List", ""]
    lines += [
        (
            "from odyssey_schemas import ("
            if len(models) > 1
            else f"from odyssey_schemas import {models[0]}"
        )
    ]
    if len(models) > 1:
        lines += [f"    {m}," for m in models] + [")"]
    lines += [
        "",
        "",
        "class " + class_name + ":",
        '    """Generated from `'
        + "`, `".join(sorted({path for _, path, *_ in ops}))
        + '`."""',
        "",
        "    def __init__(self, transport) -> None:",
        "        self._transport = transport",
        "",
    ]
    for method_name, path, params, model, is_list in ops:
        sig = ", ".join(["self"] + [f"{p}: str" for p in params])
        return_type = f"List[{model}]" if is_list else model
        path_literal = f'f"{path}"' if params else f'"{path}"'
        lines += [f"    def {method_name}({sig}) -> {return_type}:"]
        lines += [f"        data = self._transport.get({path_literal})"]
        if is_list:
            lines += [f"        return [{model}.model_validate(x) for x in data]"]
        else:
            lines += [f"        return {model}.model_validate(data)"]
        lines += [""]
    return "\n".join(lines).rstrip() + "\n"


def render_all(openapi: Dict[str, Any]) -> Dict[str, str]:
    return {
        resource: render_resource(resource, ops)
        for resource, ops in _operations_by_resource(openapi).items()
    }


def generate() -> Dict[str, Path]:
    rendered = render_all(load_openapi())
    written = {}
    for resource, content in rendered.items():
        path = _RESOURCES_DIR / f"{resource}.py"
        path.write_text(content, encoding="utf-8")
        written[resource] = path
    return written


def check_drift() -> List[str]:
    """Resources whose on-disk content no longer matches what the
    generator would produce right now — empty means no drift."""
    rendered = render_all(load_openapi())
    drifted = []
    for resource, content in rendered.items():
        path = _RESOURCES_DIR / f"{resource}.py"
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != content:
            drifted.append(resource)
    return drifted


if __name__ == "__main__":
    for resource, path in generate().items():
        print(f"wrote {path}")
