"""The generator, not the generated output — `resources/*.py` are its
product. `scripts/codegen.sh` and `odyssey sdk codegen`/`check-drift`
both call this module; nothing else should hand-edit `resources/*.py`.

Deliberately narrow: this repo's `services/api` exposes only `GET`
endpoints today (item 8.2), each returning either one object or an array
of one object type, with at most one path parameter and any number of
optional string query parameters (e.g. `/journeys?product=`). The
generator raises rather than silently guessing on anything outside that
shape — the same "narrow but real, not speculative" discipline every
other codegen-shaped module in this repo follows (`odyssey_dataprep.datasets`,
`odyssey_eval.runner`'s dynamic metric loading, etc).
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

__all__ = ["render_resource", "generate", "check_drift"]

_REPO_ROOT = Path(__file__).resolve().parents[4]
_OPENAPI_PATH = _REPO_ROOT / "services" / "api" / "openapi.json"
_RESOURCES_DIR = Path(__file__).resolve().parent / "resources"

_BANNER = (
    '"""AUTO-GENERATED by `odyssey sdk codegen` (odyssey_sdk.codegen) from\n'
    'services/api/openapi.json. Do not edit by hand — see codegen.py.\n"""\n'
)


class UnsupportedOperationError(NotImplementedError):
    pass


@dataclass(frozen=True)
class Operation:
    method_name: str
    path: str
    path_params: List[str]
    query_params: List[tuple[str, str]] = field(default_factory=list)
    model: str = ""
    is_list: bool = False


def _singular(word: str) -> str:
    return word[:-1] if word.endswith("s") else word


def _model_ref(schema: Dict[str, Any]) -> tuple[str, bool]:
    if schema.get("type") == "array":
        return schema["items"]["$ref"].rsplit("/", 1)[-1], True
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1], False
    raise UnsupportedOperationError(f"unsupported response schema: {schema}")


def _optional_query_pytype(schema: Dict[str, Any]) -> Optional[str]:
    """``str``/``int`` for an optional scalar of that JSON type, else
    ``None`` — the generator raises rather than guessing on anything else
    (see module docstring)."""
    json_to_py = {"string": "str", "integer": "int"}
    if schema.get("type") in json_to_py:
        return json_to_py[schema["type"]]
    any_of = schema.get("anyOf")
    if any_of:
        types = {s.get("type") for s in any_of}
        for json_type, py_type in json_to_py.items():
            if types == {json_type, "null"}:
                return py_type
    return None


def load_openapi() -> Dict[str, Any]:
    return json.loads(_OPENAPI_PATH.read_text(encoding="utf-8"))


def _operations_by_resource(openapi: Dict[str, Any]) -> Dict[str, List[Operation]]:
    """``{resource: [Operation, ...]}``.

    ``resource`` is a path's first segment (``/journeys/{id}`` and
    ``/journeys`` both belong to ``journeys``); ``/health`` has no
    resource grouping and is skipped here (hand-written on `OdysseySDK`
    itself — see `client.py`).
    """
    by_resource: Dict[str, List[Operation]] = {}
    method_names_by_resource: Dict[str, Dict[str, str]] = {}
    for path, methods in sorted(openapi["paths"].items()):
        segments = [s for s in path.split("/") if s]
        if segments == ["health"]:
            continue
        if list(methods.keys()) != ["get"]:
            raise UnsupportedOperationError(
                f"{path}: only a single GET operation per path is supported, got {list(methods)}"
            )
        op = methods["get"]
        path_params = [
            p["name"] for p in op.get("parameters", []) if p.get("in") == "path"
        ]
        if len(path_params) > 1:
            raise UnsupportedOperationError(f"{path}: more than one path parameter")
        query_params = []
        for p in op.get("parameters", []):
            if p.get("in") != "query":
                continue
            pytype = _optional_query_pytype(p.get("schema", {}))
            if pytype is None:
                raise UnsupportedOperationError(
                    f"{path}: query parameter {p['name']!r} must be an optional string or integer"
                )
            query_params.append((p["name"], pytype))
        schema = op["responses"]["200"]["content"]["application/json"]["schema"]
        model, is_list = _model_ref(schema)

        resource = segments[0]
        if path_params:
            method_name = "get"
        elif len(segments) > 1:
            # e.g. `/journeys/counts` -> `counts()`, distinct from the
            # resource-root `/journeys` -> `list()` on the same class.
            method_name = segments[-1]
        else:
            method_name = "list"

        used_names = method_names_by_resource.setdefault(resource, {})
        if method_name in used_names:
            raise UnsupportedOperationError(
                f"{path}: derived method name {method_name!r} collides with "
                f"{used_names[method_name]!r} on resource {resource!r} — "
                "rename one of the routes' last path segment so generated "
                "methods don't clobber each other"
            )
        used_names[method_name] = path

        by_resource.setdefault(resource, []).append(
            Operation(method_name, path, path_params, query_params, model, is_list)
        )
    return by_resource


def render_resource(resource: str, ops: List[Operation]) -> str:
    models = sorted({op.model for op in ops})
    class_name = "".join(p.capitalize() for p in resource.split("_")) + "Resource"
    has_query_params = any(op.query_params for op in ops)

    lines = [_BANNER, "from __future__ import annotations", ""]
    typing_imports = (["List"] if any(op.is_list for op in ops) else []) + (
        ["Optional"] if has_query_params else []
    )
    if typing_imports:
        lines += [f"from typing import {', '.join(typing_imports)}", ""]
    if has_query_params:
        lines += ["from urllib.parse import urlencode", ""]
    lines += [
        (
            "from odyssey_schemas import ("
            if len(models) > 1
            else f"from odyssey_schemas import {models[0]}"
        )
    ]
    if len(models) > 1:
        lines += [f"    {m}," for m in models] + [")"]
    lines += [
        "",
        "",
        "class " + class_name + ":",
        '    """Generated from `'
        + "`, `".join(sorted({op.path for op in ops}))
        + '`."""',
        "",
        "    def __init__(self, transport) -> None:",
        "        self._transport = transport",
        "",
    ]
    for op in ops:
        sig_parts = ["self"] + [f"{p}: str" for p in op.path_params]
        if op.query_params:
            sig_parts += ["*"] + [f"{q}: Optional[{t}] = None" for q, t in op.query_params]
        sig = ", ".join(sig_parts)
        return_type = f"List[{op.model}]" if op.is_list else op.model
        lines += [f"    def {op.method_name}({sig}) -> {return_type}:"]
        if op.query_params:
            pairs = ", ".join(f'"{q}": {q}' for q, _ in op.query_params)
            lines += [f"        params = {{{pairs}}}"]
            lines += [
                "        params = {k: v for k, v in params.items() if v is not None}"
            ]
            lines += ['        query = ("?" + urlencode(params)) if params else ""']
            path_literal = f'f"{op.path}{{query}}"'
        else:
            path_literal = f'f"{op.path}"' if op.path_params else f'"{op.path}"'
        lines += [f"        data = self._transport.get({path_literal})"]
        if op.is_list:
            lines += [f"        return [{op.model}.model_validate(x) for x in data]"]
        else:
            lines += [f"        return {op.model}.model_validate(data)"]
        lines += [""]
    return "\n".join(lines).rstrip() + "\n"


def render_all(openapi: Dict[str, Any]) -> Dict[str, str]:
    return {
        resource: render_resource(resource, ops)
        for resource, ops in _operations_by_resource(openapi).items()
    }


def generate() -> Dict[str, Path]:
    rendered = render_all(load_openapi())
    written = {}
    for resource, content in rendered.items():
        path = _RESOURCES_DIR / f"{resource}.py"
        path.write_text(content, encoding="utf-8")
        written[resource] = path
    return written


def check_drift() -> List[str]:
    """Resources whose on-disk content no longer matches what the
    generator would produce right now — empty means no drift."""
    rendered = render_all(load_openapi())
    drifted = []
    for resource, content in rendered.items():
        path = _RESOURCES_DIR / f"{resource}.py"
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != content:
            drifted.append(resource)
    return drifted


if __name__ == "__main__":
    for resource, path in generate().items():
        print(f"wrote {path}")
