// AUTO-GENERATED by `pnpm --filter @odyssey/sdk codegen` (src/codegen.ts) from
// services/api/openapi.json. Do not edit by hand — see codegen.ts.

import type { Transport } from "../client.js";
import type { ExportArtifactOut } from "../types.generated.js";

/** Generated from `/exports`. */
export class ExportsResource {
  constructor(private readonly transport: Transport) {}

  async list(): Promise<ExportArtifactOut[]> {
    return this.transport.get<ExportArtifactOut[]>("/exports");
  }
}
