// AUTO-GENERATED by `pnpm --filter @odyssey/sdk codegen` (src/codegen.ts) from
// services/api/openapi.json. Do not edit by hand — see codegen.ts.

import type { Transport } from "../client.js";
import type { JourneyDetailOut, JourneySummaryOut } from "../types.generated.js";

/** Generated from `/journeys`, `/journeys/{journey_id}`. */
export class JourneysResource {
  constructor(private readonly transport: Transport) {}

  async list(options: { product?: string } = {}): Promise<JourneySummaryOut[]> {
    const params = new URLSearchParams();
    if (options.product != null) params.set("product", options.product);
    const query = params.toString() ? `?${params.toString()}` : "";
    return this.transport.get<JourneySummaryOut[]>(`/journeys${query}`);
  }

  async get(journey_id: string): Promise<JourneyDetailOut> {
    return this.transport.get<JourneyDetailOut>(`/journeys/${journey_id}`);
  }
}
