// AUTO-GENERATED by `pnpm --filter @odyssey/sdk codegen` (src/codegen.ts) from
// services/api/openapi.json. Do not edit by hand — see codegen.ts.

import type { Transport } from "../client.js";
import type { MetricsSnapshotOut } from "../types.generated.js";

/** Generated from `/metrics`. */
export class MetricsResource {
  constructor(private readonly transport: Transport) {}

  async list(options: { product?: string } = {}): Promise<MetricsSnapshotOut[]> {
    const params = new URLSearchParams();
    if (options.product != null) params.set("product", options.product);
    const query = params.toString() ? `?${params.toString()}` : "";
    return this.transport.get<MetricsSnapshotOut[]>(`/metrics${query}`);
  }
}
