// AUTO-GENERATED by `pnpm --filter @odyssey/sdk codegen` (src/codegen.ts) from
// services/api/openapi.json. Do not edit by hand — see codegen.ts.

import type { Transport } from "../client.js";
import type { ModelOut } from "../types.generated.js";

/** Generated from `/models`, `/models/{name}`. */
export class ModelsResource {
  constructor(private readonly transport: Transport) {}

  async list(): Promise<ModelOut[]> {
    return this.transport.get<ModelOut[]>("/models");
  }

  async get(name: string): Promise<ModelOut> {
    return this.transport.get<ModelOut>(`/models/${name}`);
  }
}
