// AUTO-GENERATED by `pnpm --filter @odyssey/sdk codegen` (src/codegen.ts) from
// services/api/openapi.json. Do not edit by hand — see codegen.ts.

import type { Transport } from "../client.js";
import type { ProductOut } from "../types.generated.js";

/** Generated from `/products`. */
export class ProductsResource {
  constructor(private readonly transport: Transport) {}

  async list(): Promise<ProductOut[]> {
    return this.transport.get<ProductOut[]>("/products");
  }
}
