// AUTO-GENERATED by `pnpm --filter @odyssey/sdk codegen` (src/codegen.ts) from
// services/api/openapi.json. Do not edit by hand — see codegen.ts.

import type { Transport } from "../client.js";
import type { EvalRunOut } from "../types.generated.js";

/** Generated from `/runs`. */
export class RunsResource {
  constructor(private readonly transport: Transport) {}

  async list(): Promise<EvalRunOut[]> {
    return this.transport.get<EvalRunOut[]>("/runs");
  }
}
