/**
 * The generator, not the generated output — `types.generated.ts` and
 * `resources/*.ts` are its product. `scripts/codegen.mjs` calls this
 * module; nothing else should hand-edit those files. Mirrors
 * `sdk/python/src/odyssey_sdk/codegen.py` 1:1 so both SDKs come from the
 * same narrow reading of `services/api/openapi.json`: GET-only, at most
 * one path parameter, one object or array-of-object response per
 * operation. Anything outside that shape raises instead of guessing.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..", "..");
const OPENAPI_PATH = join(REPO_ROOT, "services", "api", "openapi.json");
const SRC_DIR = join(__dirname);
const RESOURCES_DIR = join(SRC_DIR, "resources");

export class UnsupportedOperationError extends Error {}

interface JsonSchema {
  type?: string;
  $ref?: string;
  anyOf?: JsonSchema[];
  items?: JsonSchema;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  title?: string;
}

interface OpenAPIDoc {
  paths: Record<string, Record<string, any>>;
  components: { schemas: Record<string, JsonSchema> };
}

type QueryParam = { name: string; type: "string" | "number" };

type Operation = {
  methodName: string;
  path: string;
  params: string[];
  queryParams: QueryParam[];
  model: string;
  isList: boolean;
};

const BANNER =
  "// AUTO-GENERATED by `pnpm --filter @odyssey/sdk codegen` (src/codegen.ts) from\n" +
  "// services/api/openapi.json. Do not edit by hand — see codegen.ts.\n";

export function loadOpenapi(): OpenAPIDoc {
  return JSON.parse(readFileSync(OPENAPI_PATH, "utf-8"));
}

const JSON_TO_TS_SCALAR: Record<string, "string" | "number"> = {
  string: "string",
  integer: "number",
};

function optionalQueryTsType(schema: JsonSchema): "string" | "number" | null {
  if (schema.type && schema.type in JSON_TO_TS_SCALAR) {
    return JSON_TO_TS_SCALAR[schema.type];
  }
  if (schema.anyOf) {
    const types = new Set(schema.anyOf.map((s) => s.type));
    for (const [jsonType, tsType] of Object.entries(JSON_TO_TS_SCALAR)) {
      if (types.size === 2 && types.has(jsonType) && types.has("null")) {
        return tsType;
      }
    }
  }
  return null;
}

function modelRef(schema: JsonSchema): { model: string; isList: boolean } {
  if (schema.type === "array") {
    if (!schema.items?.$ref) {
      throw new UnsupportedOperationError(`unsupported array items: ${JSON.stringify(schema)}`);
    }
    return { model: schema.items.$ref.split("/").pop()!, isList: true };
  }
  if (schema.$ref) {
    return { model: schema.$ref.split("/").pop()!, isList: false };
  }
  throw new UnsupportedOperationError(`unsupported response schema: ${JSON.stringify(schema)}`);
}

export function operationsByResource(openapi: OpenAPIDoc): Record<string, Operation[]> {
  const byResource: Record<string, Operation[]> = {};
  for (const path of Object.keys(openapi.paths).sort()) {
    const methods = openapi.paths[path];
    const segments = path.split("/").filter(Boolean);
    if (segments.length === 1 && segments[0] === "health") {
      continue;
    }
    const methodNames = Object.keys(methods);
    if (methodNames.length !== 1 || methodNames[0] !== "get") {
      throw new UnsupportedOperationError(
        `${path}: only a single GET operation per path is supported, got ${methodNames}`,
      );
    }
    const op = methods.get;
    const params: string[] = (op.parameters ?? [])
      .filter((p: any) => p.in === "path")
      .map((p: any) => p.name);
    if (params.length > 1) {
      throw new UnsupportedOperationError(`${path}: more than one path parameter`);
    }
    const queryParams: QueryParam[] = [];
    for (const p of op.parameters ?? []) {
      if (p.in !== "query") continue;
      const type = optionalQueryTsType(p.schema ?? {});
      if (!type) {
        throw new UnsupportedOperationError(
          `${path}: query parameter ${p.name} must be an optional string or integer`,
        );
      }
      queryParams.push({ name: p.name, type });
    }
    const schema = op.responses["200"].content["application/json"].schema;
    const { model, isList } = modelRef(schema);
    const resource = segments[0];
    let methodName: string;
    if (params.length) {
      methodName = "get";
    } else if (segments.length > 1) {
      // e.g. `/journeys/counts` -> `counts()`, distinct from the
      // resource-root `/journeys` -> `list()` on the same class.
      methodName = segments[segments.length - 1];
    } else {
      methodName = "list";
    }
    (byResource[resource] ??= []).push({
      methodName,
      path,
      params,
      queryParams,
      model,
      isList,
    });
  }
  return byResource;
}

function capitalize(word: string): string {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

export function renderResource(resource: string, ops: Operation[]): string {
  const models = [...new Set(ops.map((o) => o.model))].sort();
  const className = ops[0] ? capitalize(resource) + "Resource" : capitalize(resource) + "Resource";
  const paths = [...new Set(ops.map((o) => o.path))].sort();

  const lines: string[] = [
    BANNER,
    `import type { Transport } from "../client.js";`,
    `import type { ${models.join(", ")} } from "../types.generated.js";`,
    "",
    `/** Generated from \`${paths.join("\`, \`")}\`. */`,
    `export class ${className} {`,
    `  constructor(private readonly transport: Transport) {}`,
    "",
  ];
  for (const { methodName, path, params, queryParams, model, isList } of ops) {
    const sigParts = params.map((p) => `${p}: string`);
    if (queryParams.length) {
      const optionsType = queryParams.map((q) => `${q.name}?: ${q.type}`).join("; ");
      sigParts.push(`options: { ${optionsType} } = {}`);
    }
    const sig = sigParts.join(", ");
    const returnType = isList ? `${model}[]` : model;
    const pathTemplate = path.replace(/{([^}]+)}/g, (_, p) => `\${${p}}`);
    const pathExpr = params.length ? "`" + pathTemplate + "`" : `"${path}"`;
    lines.push(`  async ${methodName}(${sig}): Promise<${returnType}> {`);
    if (queryParams.length) {
      lines.push(`    const params = new URLSearchParams();`);
      for (const q of queryParams) {
        lines.push(`    if (options.${q.name} != null) params.set("${q.name}", String(options.${q.name}));`);
      }
      lines.push(`    const query = params.toString() ? \`?\${params.toString()}\` : "";`);
      lines.push(`    return this.transport.get<${returnType}>(\`${pathTemplate}\${query}\`);`);
    } else {
      lines.push(`    return this.transport.get<${returnType}>(${pathExpr});`);
    }
    lines.push(`  }`);
    lines.push("");
  }
  if (lines[lines.length - 1] === "") {
    lines.pop();
  }
  lines.push("}");
  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

function tsPrimitive(schema: JsonSchema): string {
  if (schema.anyOf) {
    return schema.anyOf.map(tsPrimitive).join(" | ");
  }
  if (schema.$ref) {
    return schema.$ref.split("/").pop()!;
  }
  if (schema.type === "array") {
    return `${tsPrimitive(schema.items!)}[]`;
  }
  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    default:
      throw new UnsupportedOperationError(`unsupported schema: ${JSON.stringify(schema)}`);
  }
}

export function renderTypes(openapi: OpenAPIDoc): string {
  const lines: string[] = [BANNER, ""];
  const names = Object.keys(openapi.components.schemas)
    .filter((n) => n !== "HTTPValidationError" && n !== "ValidationError")
    .sort();
  for (const name of names) {
    const schema = openapi.components.schemas[name];
    const required = new Set(schema.required ?? []);
    lines.push(`export interface ${name} {`);
    for (const [field, fieldSchema] of Object.entries(schema.properties ?? {})) {
      const optional = required.has(field) ? "" : "?";
      lines.push(`  ${field}${optional}: ${tsPrimitive(fieldSchema)};`);
    }
    lines.push("}", "");
  }
  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

export function renderAll(openapi: OpenAPIDoc): { types: string; resources: Record<string, string> } {
  const resources: Record<string, string> = {};
  for (const [resource, ops] of Object.entries(operationsByResource(openapi))) {
    resources[resource] = renderResource(resource, ops);
  }
  return { types: renderTypes(openapi), resources };
}

export function generate(): string[] {
  const { types, resources } = renderAll(loadOpenapi());
  if (!existsSync(RESOURCES_DIR)) {
    mkdirSync(RESOURCES_DIR, { recursive: true });
  }
  writeFileSync(join(SRC_DIR, "types.generated.ts"), types, "utf-8");
  const written = [join(SRC_DIR, "types.generated.ts")];
  for (const [resource, content] of Object.entries(resources)) {
    const path = join(RESOURCES_DIR, `${resource}.ts`);
    writeFileSync(path, content, "utf-8");
    written.push(path);
  }
  return written;
}

export function checkDrift(): string[] {
  const { types, resources } = renderAll(loadOpenapi());
  const drifted: string[] = [];
  const typesPath = join(SRC_DIR, "types.generated.ts");
  const currentTypes = existsSync(typesPath) ? readFileSync(typesPath, "utf-8") : "";
  if (currentTypes !== types) {
    drifted.push("types.generated.ts");
  }
  for (const [resource, content] of Object.entries(resources)) {
    const path = join(RESOURCES_DIR, `${resource}.ts`);
    const current = existsSync(path) ? readFileSync(path, "utf-8") : "";
    if (current !== content) {
      drifted.push(resource);
    }
  }
  return drifted;
}
