// AUTO-GENERATED by `pnpm --filter @odyssey/sdk codegen` (src/codegen.ts) from
// services/api/openapi.json. Do not edit by hand — see codegen.ts.

export interface DatasetOut {
  name: string;
  versions: DatasetVersionOut[];
}

export interface DatasetVersionOut {
  manifest_sha256: string;
  uri: string;
  version: number;
}

export interface EvalRunOut {
  benchmark_name: string;
  mean_score: number;
  metric_name: string;
  report_path: string;
}

export interface ExportArtifactOut {
  name: string;
  path: string;
  rows: number;
  sha256: string;
}

export interface HealthOut {
  status: string;
}

export interface JourneyDetailOut {
  complete: boolean;
  incomplete_reason?: string | null;
  journey_id: string;
  metrics: JourneyMetricsOut;
  steps: StepOut[];
}

export interface JourneyMetricsOut {
  aggregated_reward?: number | null;
  num_tool_calls?: number | null;
  num_tool_failures?: number | null;
  steps?: number | null;
  tool_error_rate?: number | null;
}

export interface JourneySummaryOut {
  complete: boolean;
  date: string;
  journey_id: string;
}

export interface ModelOut {
  name: string;
  versions: ModelVersionOut[];
}

export interface ModelVersionOut {
  base_model?: string | null;
  corpus_version?: string | null;
  sha256: string;
  uri: string;
  version: number;
}

export interface StepOut {
  index: number;
  message_count: number;
  trainable_status: string;
}
