"""AUTO-GENERATED by `odyssey sdk codegen` (odyssey_sdk.codegen) from
services/api/openapi.json. Do not edit by hand — see codegen.py.
"""

from __future__ import annotations

from typing import Optional
from urllib.parse import urlencode

from odyssey_schemas import ExportPageOut


class ExportsResource:
    """Generated from `/exports`."""

    def __init__(self, transport) -> None:
        self._transport = transport

    def list(
        self, *, cursor: Optional[str] = None, limit: Optional[int] = None
    ) -> ExportPageOut:
        params = {"cursor": cursor, "limit": limit}
        params = {k: v for k, v in params.items() if v is not None}
        query = ("?" + urlencode(params)) if params else ""
        data = self._transport.get(f"/exports{query}")
        return ExportPageOut.model_validate(data)
