"""AUTO-GENERATED by `odyssey sdk codegen` (odyssey_sdk.codegen) from
services/api/openapi.json. Do not edit by hand — see codegen.py.
"""

from __future__ import annotations

from typing import List

from odyssey_schemas import ExportArtifactOut


class ExportsResource:
    """Generated from `/exports`."""

    def __init__(self, transport) -> None:
        self._transport = transport

    def list(self) -> List[ExportArtifactOut]:
        data = self._transport.get("/exports")
        return [ExportArtifactOut.model_validate(x) for x in data]
