"""AUTO-GENERATED by `odyssey sdk codegen` (odyssey_sdk.codegen) from
services/api/openapi.json. Do not edit by hand — see codegen.py.
"""

from __future__ import annotations

from typing import List

from odyssey_schemas import (
    JourneyDetailOut,
    JourneySummaryOut,
)


class JourneysResource:
    """Generated from `/journeys`, `/journeys/{journey_id}`."""

    def __init__(self, transport) -> None:
        self._transport = transport

    def list(self) -> List[JourneySummaryOut]:
        data = self._transport.get("/journeys")
        return [JourneySummaryOut.model_validate(x) for x in data]

    def get(self, journey_id: str) -> JourneyDetailOut:
        data = self._transport.get(f"/journeys/{journey_id}")
        return JourneyDetailOut.model_validate(data)
