"""AUTO-GENERATED by `odyssey sdk codegen` (odyssey_sdk.codegen) from
services/api/openapi.json. Do not edit by hand — see codegen.py.
"""

from __future__ import annotations

from typing import Optional

from urllib.parse import urlencode

from odyssey_schemas import (
    CountsOut,
    JourneyDetailOut,
    JourneyPageOut,
)


class JourneysResource:
    """Generated from `/journeys`, `/journeys/counts`, `/journeys/{journey_id}`."""

    def __init__(self, transport) -> None:
        self._transport = transport

    def list(self, *, product: Optional[str] = None, date: Optional[str] = None, cursor: Optional[str] = None, limit: Optional[int] = None) -> JourneyPageOut:
        params = {"product": product, "date": date, "cursor": cursor, "limit": limit}
        params = {k: v for k, v in params.items() if v is not None}
        query = ("?" + urlencode(params)) if params else ""
        data = self._transport.get(f"/journeys{query}")
        return JourneyPageOut.model_validate(data)

    def counts(self) -> CountsOut:
        data = self._transport.get("/journeys/counts")
        return CountsOut.model_validate(data)

    def get(self, journey_id: str) -> JourneyDetailOut:
        data = self._transport.get(f"/journeys/{journey_id}")
        return JourneyDetailOut.model_validate(data)
