"""AUTO-GENERATED by `odyssey sdk codegen` (odyssey_sdk.codegen) from
services/api/openapi.json. Do not edit by hand — see codegen.py.
"""

from __future__ import annotations

from typing import List

from odyssey_schemas import ModelOut


class ModelsResource:
    """Generated from `/models`, `/models/{name}`."""

    def __init__(self, transport) -> None:
        self._transport = transport

    def list(self) -> List[ModelOut]:
        data = self._transport.get("/models")
        return [ModelOut.model_validate(x) for x in data]

    def get(self, name: str) -> ModelOut:
        data = self._transport.get(f"/models/{name}")
        return ModelOut.model_validate(data)
